closet/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'closet'

urlpatterns = [
    path('', views.ClosetListView.as_view(), name='closet_list'),  # 显示衣橱列表
    path('add/', views.ClothingCreateView.as_view(), name='clothing_add'),  # 添加衣物
    path('<int:pk>/edit/', views.ClothingUpdateView.as_view(), name='clothing_edit'),  # 编辑衣物
    path('<int:pk>/delete_ajax/', views.ajax_clothing_delete, name='clothing_delete_ajax'),  # 删除衣物
    path('ajax/get_clothing_items/', views.get_clothing_items, name='get_clothing_items'),
    path('get_item_details/', views.get_item_details, name='get_item_details'),

 ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fashionize/urls.py

from django.contrib import admin
from django.template.context_processors import media
from django.urls import path, include
from django.urls.conf import re_path
from django.conf.urls.static import static
from django.conf import settings
from account import views
from closet import views as closet_views
from outfits import views as outfits_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('manage/', views.manage_account, name='manage_account'),
    # path('media/<str:username>/<str:clothing_type>/<str:filename>', closet_views.serve_protected_media, name='serve_protected_media'),
    # path('media/<str:username>/outfit_images/<str:filename>', outfits_views.serve_protected_media, name='serve_protected_media_outfit'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
]

urlpatterns += [
    re_path(r'^(?P<username>\w+)/closet/', include('closet.urls')),
    re_path(r'^(?P<username>[^/]+)/myaccount/$', views.manage_account, name='manage_account'),
    re_path(r'^(?P<username>\w+)/dashboard/', include('dashboard.urls')),
    re_path(r'^(?P<username>\w+)/outfits/', include('outfits.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



outfits/urls.py
from django.urls import path
from .views import OutfitListView, OutfitCreateView, delete_outfit, OutfitUpdateView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'outfits'

urlpatterns = [
    path('', OutfitListView.as_view(), name='my_outfits'),
    path('create/', OutfitCreateView.as_view(), name='create_outfit'),
    path('<int:pk>/delete/', delete_outfit, name='delete_outfit'),
    path('<int:pk>/edit/', OutfitUpdateView.as_view(), name='update_outfit'),
]

outfits/models.py
from django.db import models
from django.conf import settings

def user_directory_path(instance, filename):
    # upload MEDIA_ROOT/username/outfit_images
    return '{0}/outfit_images/{1}'.format(instance.owner.username, filename)
class Outfit(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='outfits')
    name = models.CharField(max_length=100)
    top = models.ForeignKey('closet.Clothing', on_delete=models.SET_NULL, null=True, related_name='outfit_tops', limit_choices_to={'type': 'top'})
    bottom = models.ForeignKey('closet.Clothing', on_delete=models.SET_NULL, null=True, related_name='outfit_bottoms', limit_choices_to={'type': 'bottom'})
    shoe = models.ForeignKey('closet.Clothing', on_delete=models.SET_NULL, null=True, related_name='outfit_shoes', limit_choices_to={'type': 'shoe'})
    image = models.ImageField(upload_to=user_directory_path)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


outfits/forms.py
from django import forms
from .models import Outfit
from closet.models import Clothing

class OutfitForm(forms.ModelForm):
    top = forms.ModelChoiceField(
        queryset=Clothing.objects.none(),  # 初始时为空，将在 __init__ 中设置
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Top"
    )
    bottom = forms.ModelChoiceField(
        queryset=Clothing.objects.none(),  # 初始时为空，将在 __init__ 中设置
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Bottom"
    )
    shoe = forms.ModelChoiceField(
        queryset=Clothing.objects.none(),  # 初始时为空，将在 __init__ 中设置
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Shoe"
    )

    class Meta:
        model = Outfit
        fields = ['name', 'top', 'bottom', 'shoe', 'image']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            # 'image' 字段如果需要用户上传，则可以在这里定义相应的 widget
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # 从视图传递的user参数
        super(OutfitForm, self).__init__(*args, **kwargs)

        # 根据当前用户过滤衣物选项
        if user:
            self.fields['top'].queryset = Clothing.objects.filter(owner=user, type='top')
            self.fields['bottom'].queryset = Clothing.objects.filter(owner=user, type='bottom')
            self.fields['shoe'].queryset = Clothing.objects.filter(owner=user, type='shoe')

        # 如果需要，这里还可以添加其他初始化逻辑


outfits/views.py
import os
from io import BytesIO

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.base import ContentFile
from django.http import JsonResponse, HttpResponseNotAllowed, Http404, FileResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from fashionize import settings
from .models import Outfit
from django.urls import reverse_lazy, reverse
from .forms import OutfitForm


class OutfitListView(LoginRequiredMixin, ListView):
    model = Outfit
    context_object_name = 'outfits'
    template_name = 'outfits/my_outfits.html'

    def get_queryset(self):
        query_set = super().get_queryset().filter(owner=self.request.user)
        sort = self.request.GET.get('sort', 'name')

        if sort == 'created_at':
            query_set = query_set.order_by('-created_at')
        else:  # 默认按名称排序
            query_set = query_set.order_by('name')

        return query_set





class OutfitCreateView(CreateView):
        model = Outfit
        form_class = OutfitForm
        template_name = 'outfits/create_outfit.html'

        def form_valid(self, form):
            form.instance.owner = self.request.user
            # 直接保存表单，不需要调用 process_and_synthesize_images
            response = super().form_valid(form)
            return response

        def get_success_url(self):
            # 动态生成重定向URL，确保包含用户名
            username = self.request.user.username
            return reverse('outfits:my_outfits', kwargs={'username': username})


def delete_outfit(request, username, pk):
    if request.method == 'POST':
        outfit = get_object_or_404(Outfit, pk=pk, owner=request.user)
        outfit.delete()
        return JsonResponse({'status': 'success', 'message': 'Outfit deleted successfully'})
    else:
        return HttpResponseNotAllowed(['POST'])

class OutfitUpdateView(LoginRequiredMixin, UpdateView):
    model = Outfit
    form_class = OutfitForm
    template_name = 'outfits/update_outfit.html'

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Outfit, pk=pk, owner=self.request.user)

    def form_valid(self, form):
        form.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('outfits:my_outfits', kwargs={'username': self.request.user.username})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        outfit = self.get_object()
        context['top_image_url'] = outfit.top.image.url if outfit.top else ''
        context['bottom_image_url'] = outfit.bottom.image.url if outfit.bottom else ''
        context['shoe_image_url'] = outfit.shoe.image.url if outfit.shoe else ''
        return context


@login_required
def serve_protected_media(request, username, filename):
    if request.user.username != username:
        raise Http404("You do not have permission to access this file.")

    # Check if the request is for outfit images
    if 'outfit_images' in filename:
        # The path for outfit images
        file_path = os.path.join(settings.MEDIA_ROOT, username, 'outfit_images', filename)
    else:
        # The path for clothing images (top, bottom, shoe)
        file_path = os.path.join(settings.MEDIA_ROOT, username, filename)

    if os.path.exists(file_path):
        # Return the file if it exists
        return FileResponse(open(file_path, 'rb'), content_type='image/jpeg')
    else:
        # If the file does not exist, return a 404 error
        raise Http404("File not found.")

templates/outfits/create_outfit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/create_outfit.css' %}">
{% endblock %}

{% block extra_js %}
<script src="{% static 'javascript/create_outfit.js' %}"></script>
<script>
    const username = "{{ request.user.username }}";
</script>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8">
            <div class="clothing-selection mb-3">
                <div class="clothing-grid top" data-type="top" onclick="openSelectionModal('top')">Top Selection Area</div>
                <div class="clothing-grid bottom" data-type="bottom" onclick="openSelectionModal('bottom')">Bottom Selection Area</div>
                <div class="clothing-grid shoe" data-type="shoe" onclick="openSelectionModal('shoe')">Shoe Selection Area</div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="outfit-details">
                <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_name" class="form-label">Name:</label>
                        {{ form.name|add_class:"form-control" }}
                    </div>
                    <div class="mb-3">
                        <label for="id_image" class="form-label">Photo:</label>
                        {{ form.image|add_class:"form-control" }}
                    </div>
                    <div class="d-none">
                        {{ form.top }}
                        {{ form.bottom }}
                        {{ form.shoe }}
                    </div>
                    <button type="submit" class="btn btn-primary">Create Outfit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- 模态框用于衣物选择 -->
<div class="modal fade" id="clothing-selection-modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Select Clothing Item</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="clothing-selection-content"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/outfits/my_outfits.html
{% extends 'base.html' %}
{% load static %}

{% block extra_js %}
<script src="{% static 'javascript/select_and_delete_outfit.js' %}"></script>
<script>
    const username = "{{ request.user.username }}";
</script>
{% endblock %}
{% block extra_css %}
 <link rel="stylesheet" href="{% static 'css/closet_list.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>My Outfits</h2>
    <!-- 添加排序功能 -->
    <div class="sorting mb-3">
        <form class="form-inline" method="get">
            <label for="sort" class="mr-2">Sort by:</label>
            <select name="sort" class="form-control" onchange="this.form.submit()">
                <option value="name" {% if request.GET.sort == 'name' %}selected{% endif %}>Name</option>
                <option value="created_at" {% if request.GET.sort == 'created_at' %}selected{% endif %}>Added Time</option>
            </select>
        </form>
    </div>

    <a href="{% url 'outfits:create_outfit' username=request.user.username %}" class="btn btn-primary mb-3">Add New Outfit</a>
    <div class="row">
        {% for outfit in outfits %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img src="{{ outfit.image.url }}" class="card-img-top" alt="{{ outfit.name }}">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ outfit.name }}</h5>
                    <a href="{% url 'outfits:update_outfit' username=request.user.username pk=outfit.pk %}" class="btn btn-secondary">Edit</a>
                    <button type="button" class="btn btn-danger delete-btn" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal" data-outfit-id="{{ outfit.pk }}">Delete</button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this outfit?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" id="confirmDeleteButton">Delete</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/outfits/update_outfit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/update_outfit.css' %}">
{% endblock %}

{% block extra_js %}
<script src="{% static 'javascript/update_outfit.js' %}"></script>
<script>
    const username = "{{ request.user.username }}";
    const selectedTopImageUrl = "{{ outfit.top.image.url|default_if_none:'' }}";
    const selectedBottomImageUrl = "{{ outfit.bottom.image.url|default_if_none:'' }}";
    const selectedShoeImageUrl = "{{ outfit.shoe.image.url|default_if_none:'' }}";
</script>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 clothing-selection">
            <div class="mb-3" data-type="top" onclick="openSelectionModal('top')">
                <div class="clothing-grid top" style="background-image: url('{{selectedTopImageUrl}}');"></div>
                Top Selection Area
            </div>
            <div class="mb-3" data-type="bottom" onclick="openSelectionModal('bottom')">
                <div class="clothing-grid bottom" style="background-image: url('{{selectedBottomImageUrl}}');"></div>
                Bottom Selection Area
            </div>
            <div class="mb-3" data-type="shoe" onclick="openSelectionModal('shoe')">
                <div class="clothing-grid shoe" style="background-image: url('{{selectedShoeImageUrl}}');"></div>
                Shoe Selection Area
            </div>
        </div>
        <div class="col-md-6 outfit-details">
            <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_name" class="form-label">Name:</label>
                    {{ form.name|add_class:"form-control" }}
                </div>
                <div class="mb-3">
                    <label for="id_image" class="form-label">Image:</label>
                    {{ form.image|add_class:"form-control" }}
                </div>
                <div class="d-none">
                    {{ form.top }}
                    {{ form.bottom }}
                    {{ form.shoe }}
                </div>
                <button type="submit" class="btn btn-primary">Update Outfit</button>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="clothing-selection-modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Select Clothing Item</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="clothing-selection-content"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}