closet/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'closet'

urlpatterns = [
    path('', views.ClosetListView.as_view(), name='closet_list'),  # 显示衣橱列表
    path('add/', views.ClothingCreateView.as_view(), name='clothing_add'),  # 添加衣物
    path('<int:pk>/edit/', views.ClothingUpdateView.as_view(), name='clothing_edit'),  # 编辑衣物
    path('<int:pk>/delete_ajax/', views.ajax_clothing_delete, name='clothing_delete_ajax'),  # 删除衣物
    path('ajax/get_clothing_items/', views.get_clothing_items, name='get_clothing_items'),
    path('get_item_details/', views.get_item_details, name='get_item_details'),

 ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
]

fashionize/urls.py

from django.contrib import admin
from django.template.context_processors import media
from django.urls import path, include
from django.urls.conf import re_path
from django.conf.urls.static import static
from django.conf import settings
from account import views
from closet import views as closet_views
from outfits import views as outfits_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('manage/', views.manage_account, name='manage_account'),
    # path('media/<str:username>/<str:clothing_type>/<str:filename>', closet_views.serve_protected_media, name='serve_protected_media'),
    # path('media/<str:username>/outfit_images/<str:filename>', outfits_views.serve_protected_media, name='serve_protected_media_outfit'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
]

urlpatterns += [
    re_path(r'^(?P<username>\w+)/closet/', include('closet.urls')),
    re_path(r'^(?P<username>[^/]+)/myaccount/$', views.manage_account, name='manage_account'),
    re_path(r'^(?P<username>\w+)/dashboard/', include('dashboard.urls')),
    re_path(r'^(?P<username>\w+)/outfits/', include('outfits.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



outfits/urls.py
from django.urls import path
from .views import OutfitListView, OutfitCreateView, delete_outfit, OutfitUpdateView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'outfits'

urlpatterns = [
    path('', OutfitListView.as_view(), name='my_outfits'),
    path('create/', OutfitCreateView.as_view(), name='create_outfit'),
    path('<int:pk>/delete/', delete_outfit, name='delete_outfit'),
    path('<int:pk>/edit/', OutfitUpdateView.as_view(), name='update_outfit'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load closet_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Website{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bs/css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Optional Bootstrap JavaScript and Popper.js for Bootstrap components to work -->
     <script src="{% static 'bs/js/bootstrap.bundle.min.js' %}" defer></script>
    {% block extra_js %} {% endblock %}
    {% block extra_css %} {% endblock %}

</head>
<body>

    <header class="bg-light mb-4">
        <!-- Header content like a navigation bar goes here -->
    </header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Fashionize</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                {% block nav %}
                 <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard:dashboard' username=request.user.username %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'closet:closet_list' username=request.user.username %}">My Closet</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'outfits:my_outfits' username=request.user.username %}">My Outfits</a>
                    </li>
                </ul>
                {% endblock %}
            </div>
            <ul class="navbar-nav ml-auto">
                <!-- 登出按钮 -->
                <li class="nav-item">
                        <a href="{% url 'manage_account' username=user.username %}" class="nav-link">Manage Account</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link btn btn-outline-danger">Logout</a>
                </li>
            </ul>
        </div>
    </nav>




    <main class="container">
        {% block content %}
        <!-- Main content goes here -->
        {% endblock %}
    </main>

    <div>
        {% block sidebar_block %}
        <!-- Sidebar content or additional tags go here -->
        {% endblock %}
    </div>

    <footer class="bg-light text-center text-lg-start">
        <div class="text-muted p-3">
            © 2024 Group Project. All rights reserved.
        </div>
    </footer>
</body>
</html>